{
 "title": "Xoa Host Overview",
 "description": "data from Openmetrics",
 "tags": [
  "xoa",
  "xcp-ng",
  "prometheus",
  "openmetrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "vm_uuids", "query": { "query": "xcp_vm_cpu_usage" } },
   { "name": "host_uuids", "query": { "query": "xcp_host_cpu_average" } }
  ]
 },
 "panels": [
  { "title": "${host_uuids:text}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host_uuids" },
  {
   "title": "Quick Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "__auto" },
    { "expr": "xcp_host_cpu_average", "legendFormat": "__auto" },
    {
     "expr": "((xcp_host_memory_total_bytes - xcp_host_memory_free_bytes)/xcp_host_memory_total_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host_name) (xcp_host_cpu_core_usage)",
     "legendFormat": "__auto"
    },
    {
     "expr": "xcp_host_memory_total_bytes - xcp_host_memory_free_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "xcp_host_cpu_core_usage", "legendFormat": "Core {{core}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xcp_host_memory_total_bytes - xcp_host_memory_free_bytes",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "xcp_host_network_receive_bytes_total",
     "legendFormat": "rx {{interface}}"
    },
    {
     "expr": "rate(xcp_host_network_transmit_bytes_total[5m])",
     "legendFormat": "tx {{interface}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xcp_sr_physical_usage_bytes{sr_name=\"Local storage\"}",
     "legendFormat": "Used {{sr_name}}"
    },
    {
     "expr": "xcp_sr_physical_size_bytes{sr_name=\"Local storage\"}",
     "legendFormat": "Total {{sr_name}}"
    }
   ]
  },
  {
   "title": "Host Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "xcp_host_disk_read_latency_seconds",
     "legendFormat": "Read {{device}}"
    }
   ]
  },
  {
   "title": "Host IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    { "expr": "xcp_host_disk_iops_read", "legendFormat": "Read {{device}}" },
    { "expr": "xcp_host_disk_iops_write", "legendFormat": "Write {{device}}" },
    { "expr": "xcp_host_disk_iowait", "legendFormat": "Write {{device}}" }
   ]
  },
  {
   "title": "Host Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "xcp_host_disk_throughput_read_bytes",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "xcp_host_disk_throughput_write_bytes",
     "legendFormat": "Write {{device}}"
    }
   ]
  }
 ]
}