{
 "title": "Xoa Vm Overview",
 "description": "data from Openmetrics",
 "tags": [
  "xoa",
  "openmetrics",
  "xcp-ng",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "vm_uuids", "query": { "query": "xcp_vm_cpu_usage" } },
   { "name": "host_uuids", "query": { "query": "xcp_host_cpu_average" } }
  ]
 },
 "panels": [
  { "title": "${vm_uuids:text}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vm_uuids" },
  {
   "title": "VM Quick Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "__auto" },
    {
     "expr": "xcp_vm_cpu_usage{uuid=\"$vm_uuids\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "((xcp_vm_memory_bytes - xcp_vm_memory_internal_free_bytes)/xcp_vm_memory_bytes{uuid=\"$vm_uuids\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(vm_name) (xcp_vm_cpu_core_usage{uuid=\"$vm_uuids\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "xcp_vm_memory_bytes - xcp_vm_memory_internal_free_bytes{uuid=\"$vm_uuids\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xcp_vm_cpu_usage{uuid=~\"$vm_uuids\"}",
     "legendFormat": "vcpu{{core}}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xcp_vm_memory_bytes{uuid=~\"$vm_uuids\"} - xcp_vm_memory_internal_free_bytes{uuid=~\"$vm_uuids\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "VM Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "xcp_vm_network_receive_bytes_total{uuid=~\"$vm_uuids\"}",
     "legendFormat": "rx {{interface}}"
    },
    {
     "expr": "rate(xcp_vm_network_transmit_bytes_total{uuid=~\"$vm_uuids\"}[5m])",
     "legendFormat": "tx {{interface}}"
    }
   ]
  },
  {
   "title": "VM Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "xcp_vm_disk_read_latency_seconds{uuid=~\"$vm_uuids\"}",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "xcp_vm_disk_write_latency_seconds{uuid=~\"$vm_uuids\"} * 1000000",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "VM IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "xcp_vm_disk_iops_read{uuid=~\"$vm_uuids\"}",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "xcp_vm_disk_iops_write{uuid=~\"$vm_uuids\"}",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "VM IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "xcp_vm_disk_read_bytes_total{uuid=~\"$vm_uuids\"}",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(xcp_vm_disk_write_bytes_total{uuid=~\"$vm_uuids\"}[5m]) / 1024 / 1024",
     "legendFormat": "Write {{device}}"
    }
   ]
  }
 ]
}