{
 "title": "Xoa SR Overview",
 "description": "data from Openmetrics",
 "tags": [
  "xoa",
  "xcp-ng",
  "openmetrics",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "sr_uuids", "query": { "query": "xcp_sr_physical_size_bytes" } }
  ]
 },
 "panels": [
  {
   "title": "SR Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(xcp_sr_physical_usage_bytes / xcp_sr_physical_size_bytes) *100 ",
     "legendFormat": "{{sr_name}}"
    }
   ]
  },
  {
   "title": "${sr_uuids:text}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "sr_uuids",
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "xcp_sr_physical_size_bytes{sr_name=\"$sr_uuids\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "xcp_sr_physical_usage_bytes{sr_name=\"$sr_uuids\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Capacity Summary",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "xcp_sr_physical_usage_bytes{sr_name=\"$sr_uuids\"}",
       "legendFormat": "Used Capacity - {{sr_name}}"
      },
      {
       "expr": "xcp_sr_physical_size_bytes{sr_name=\"$sr_uuids\"} - xcp_sr_physical_usage_bytes{sr_name=\"$sr_uuids\"}",
       "legendFormat": "Free Capacity - {{sr_name}}"
      }
     ]
    }
   ]
  }
 ]
}