{
 "title": "Xoa Cluster Overview",
 "description": "data from Openmetrics",
 "tags": [
  "xoa",
  "openmetrics",
  "prometheus",
  "xcp-ng"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "vm_uuids", "query": { "query": "xcp_vm_cpu_usage" } },
   { "name": "host_uuids", "query": { "query": "xcp_host_cpu_average" } }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Xoa Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(__name__) (xcp_vm_cpu_usage{type=\"vm\", vm_name=\"XOA\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "count_values by(__name__) (\"count\", sum by(pool_name) (xcp_host_cpu_average))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "count_values by(host_name) (\"count\", sum by(host_name) (xcp_host_cpu_average))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "count by(__name__) (xcp_vm_cpu_usage{type=\"vm\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "count((xcp_sr_physical_usage_bytes / xcp_sr_physical_size_bytes) *100  > 0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "$host_uuids Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "repeat": "host_uuids",
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xcp_host_uptime_seconds", "legendFormat": "__auto" },
    { "expr": "xcp_host_cpu_average * 100", "legendFormat": "__auto" },
    {
     "expr": "((xcp_host_memory_total_bytes - xcp_host_memory_free_bytes)/xcp_host_memory_total_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(xcp_sr_physical_usage_bytes{sr_name=\"Local storage\"} * 100 > 0) / xcp_sr_physical_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pool CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(host_name) (xcp_host_cpu_average)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Pool MEMORY Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((xcp_host_memory_total_bytes - xcp_host_memory_free_bytes)/xcp_host_memory_total_bytes)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "SR - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(xcp_sr_physical_usage_bytes / xcp_sr_physical_size_bytes) *100  > 0",
     "legendFormat": "{{sr_name}}"
    }
   ]
  },
  {
   "title": "Pool Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(xcp_host_network_receive_bytes_total{interface=\"aggr\"}[5m])",
     "legendFormat": "rx - {{host_name}}"
    },
    {
     "expr": "rate(xcp_host_network_transmit_bytes_total{interface=\"aggr\"}[5m])",
     "legendFormat": "tx - {{host_name}}"
    }
   ]
  },
  {
   "title": "Pool Storage Adapter Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(xcp_host_network_receive_bytes_total{interface=\"bond0\"}[5m])",
     "legendFormat": "rx - {{host_name}}"
    },
    {
     "expr": "rate(xcp_host_network_transmit_bytes_total{interface=\"bond0\"}[5m])",
     "legendFormat": "tx - {{host_name}}"
    }
   ]
  },
  { "title": "XCP Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Node CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(host_name) (xcp_host_cpu_core_usage)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Node MEMORY Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((xcp_host_memory_total_bytes - xcp_host_memory_free_bytes)/xcp_host_memory_total_bytes)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Node Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(xcp_host_network_receive_bytes_total{interface=\"aggr\"}[5m])",
     "legendFormat": "rx - {{host_name}}"
    },
    {
     "expr": "rate(xcp_host_network_transmit_bytes_total{interface=\"aggr\"}[5m])",
     "legendFormat": "tx - {{host_name}}"
    }
   ]
  },
  { "title": "Vms Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "TOP 5 - Vms CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, xcp_vm_cpu_usage * 100)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "TOP 5 - Vms Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ((xcp_vm_memory_bytes - xcp_vm_memory_internal_free_bytes)/xcp_vm_memory_bytes))",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "TOP 5 - Vms Storage usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ((xcp_vm_memory_bytes - xcp_vm_memory_internal_free_bytes)/xcp_vm_memory_bytes))",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(vm_name) (xcp_vm_cpu_usage)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "xcp_vm_memory_bytes - xcp_vm_memory_internal_free_bytes",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "rate(xcp_vm_disk_read_bytes_total[5m]) / 1024 / 1024",
     "legendFormat": "Read {{vm_name}} /{{device}}"
    },
    {
     "expr": "rate(xcp_vm_disk_write_bytes_total[5m]) / 1024 / 1024",
     "legendFormat": "Write {{vm_name}} /{{device}}"
    }
   ]
  },
  {
   "title": "VM CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(vm_name) (xcp_vm_cpu_core_usage)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VM Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(vm_name) (rate(xcp_vm_network_receive_bytes_total[5m]))",
     "legendFormat": "rx {{vm_name}}"
    },
    {
     "expr": "sum by(vm_name) (rate(xcp_vm_network_transmit_bytes_total[5m]))",
     "legendFormat": "tx {{vm_name}}"
    }
   ]
  },
  {
   "title": "VM IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "xcp_vm_disk_read_latency_seconds * 1000000",
     "legendFormat": "Read {{vm_name}} /{{device}}"
    },
    {
     "expr": "xcp_vm_disk_write_latency_seconds * 1000000",
     "legendFormat": "Write {{vm_name}} /{{device}}"
    }
   ]
  }
 ]
}